# 🚀 High-Speed Swarm Configuration
# Optimized for fast formation changes and aggressive movement
# Use: ros2 launch launch/enhanced_swarm_system.launch.py config_file:=config/scenarios/high_speed.yaml

swarm_controller:
  ros__parameters:
    # === FORMATION PARAMETERS ===
    formation:
      spacing: 2.0              # Tighter formation for speed
      max_followers: 3
      adaptive_spacing: true
      switch_threshold: 0.3     # Faster formation switching
    
    # === CONTROL PARAMETERS ===
    control:
      proportional_gain: 2.5    # Higher gain for responsiveness
      max_velocity: 2.5         # Higher max velocity
      velocity_smoothing: 0.1   # Less smoothing for speed
      position_tolerance: 0.3   # Looser tolerance for speed
      angle_tolerance: 0.2
      max_angular_velocity: 3.0 # Faster rotation
    
    # === LEADER PARAMETERS ===
    leader:
      radius: 6.0               # Smaller radius for tighter turns
      speed: 2.0                # Higher leader speed
      circular_motion: true
      motion_pattern: "figure_eight"  # Dynamic pattern
    
    # === OBSTACLE PARAMETERS ===
    obstacles:
      avoidance_distance: 2.5   # Closer avoidance for agility
      repulsion_gain: 1.5       # Moderate repulsion
      max_obstacles: 8          # More obstacles for challenge
      auto_cleanup: true
      cleanup_time: 8.0         # Faster cleanup
      dynamic_probability: 0.4  # More dynamic obstacles
    
    # === VISUALIZATION PARAMETERS ===
    visualization:
      trail_length: 40          # Shorter trails for performance
      update_rate: 30.0         # Higher update rate
      show_trajectories: true
      show_formation_lines: true
      robot_size: 0.3
      grid_enabled: false       # Disable grid for performance
    
    # === SAFETY PARAMETERS ===
    safety:
      collision_distance: 0.8   # Closer collision threshold
      emergency_stop: false     # Disable for high speed
      boundary_x: 15.0          # Larger boundary
      boundary_y: 15.0
      boundary_enforcement: true 